
AllCops:
  TargetRubyVersion: 3.4
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'gems/*/spec/**/*.rb'
    - 'spec/**/*'
    - 'benchmark.rb'

plugins:
  - rubocop-rake
  - rubocop-minitest

Metrics/ModuleLength:
  Max: 130

Metrics/ClassLength:
  Max: 130

Metrics/MethodLength:
  Max: 15

Metrics/AbcSize:
  Max: 20

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/PerceivedComplexity:
  Max: 10

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'

