per_listener_settings true

# MQTT, anonymous (port 1883)
listener 1883
allow_anonymous true
set_tcp_nodelay true
max_topic_alias_broker 10

# Unix socket, anonymous
listener 0 /mosquitto/sockets/mqtt.sock
allow_anonymous true
set_tcp_nodelay true
max_topic_alias_broker 10

# MQTT, password auth (port 1884)
listener 1884
password_file /mosquitto/config/passwd
allow_anonymous false
set_tcp_nodelay true

# MQTTS with custom certificate (port 8883)
listener 8883
allow_anonymous true
cafile /mosquitto/config/ssl/server.crt
certfile /mosquitto/config/ssl/server.crt
keyfile /mosquitto/config/ssl/server.key
set_tcp_nodelay true

# MQTTS with client certificate required (port 8884)
listener 8884
allow_anonymous true
cafile /mosquitto/config/ssl/server.crt
certfile /mosquitto/config/ssl/server.crt
keyfile /mosquitto/config/ssl/server.key
require_certificate true
set_tcp_nodelay true

# MQTTS with password auth (port 8885)
listener 8885
password_file /mosquitto/config/passwd
allow_anonymous false
cafile /mosquitto/config/ssl/server.crt
certfile /mosquitto/config/ssl/server.crt
keyfile /mosquitto/config/ssl/server.key
set_tcp_nodelay true

# MQTTS with default CA (port 8886)
listener 8886
allow_anonymous true
certfile /mosquitto/config/ssl/server.crt
keyfile /mosquitto/config/ssl/server.key
set_tcp_nodelay true

# MQTTS with expired certificate (port 8887)
listener 8887
allow_anonymous true
cafile /mosquitto/config/ssl/expired.crt
certfile /mosquitto/config/ssl/expired.crt
keyfile /mosquitto/config/ssl/expired.key
set_tcp_nodelay true

connection_messages true
log_type all
