name: Build
on: 
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      broker_profile:
        description: 'Mosquitto broker profile'
        required: false
        default: 'testing'
        type: choice
        options:
          - stable
          - testing

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        ruby: ['3.4']
    runs-on: ${{ matrix.os }}
    env:
      MOSQUITTO_UID: 1001
      MOSQUITTO_GID: 1001
    steps:
    - uses: actions/checkout@v4
    
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    
    - name: Clean stale gems from cache
      run: bundle clean
    
    - name: Generate mosquitto password file
      run: |
        docker run --rm --user $MOSQUITTO_UID:$MOSQUITTO_GID -v $PWD/spec/fixture/mosquitto:/mosquitto/config eclipse-mosquitto:latest mosquitto_passwd -b -c /mosquitto/config/passwd ro readonly
        ls -la spec/fixture/mosquitto/passwd
    
    - name: Run build (rubocop, docs, tests with broker)
      run: bundle exec rake
    
    - name: Show broker logs on failure
      if: failure()
      run: docker compose logs
